# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Cette PullRequest a été automatiquement marquée comme étant périmée parce qu'elle n'a pas encore été traitée.
  Elle sera fermé si aucune autre activité n'a lieu. Je vous remercie pour vos contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
